# Generated by Django 4.1 on 2025-02-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="check_out",
            field=models.DateField(null=True),
        ),
    ]
