# Generated by Django 4.1 on 2025-02-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_alter_reserva_check_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="diaria",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="quant_pessoas",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="total",
            field=models.FloatField(null=True),
        ),
    ]
