# Generated by Django 4.1 on 2025-02-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_alter_reserva_diaria_alter_reserva_quant_pessoas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="pago",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
