# Generated by Django 4.1 on 2025-02-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_alter_reserva_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospede",
            name="cpf",
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
