# Generated by Django 4.1 on 2025-02-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_alter_hospede_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospede",
            name="cpf",
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
