# Generated by Django 4.1 on 2025-02-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0007_alter_hospede_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="hospede",
            name="cpf",
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
