# Generated by Django 4.1 on 2025-02-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
