# Generated by Django 4.1 on 2025-02-25 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Consumiveis",
            fields=[
                ("id_produto", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.TextField()),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financeiro.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("data", models.DateField()),
                (
                    "id_produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financeiro.consumiveis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                ("id_venda", models.IntegerField(primary_key=True, serialize=False)),
                ("quantidade", models.IntegerField()),
                ("data", models.DateField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "id_produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financeiro.estoque",
                    ),
                ),
            ],
        ),
    ]
