# Generated by Django 4.1 on 2025-02-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Consumiveis",
            new_name="Produto",
        ),
    ]
