# Generated by Django 4.1 on 2025-02-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_rename_consumiveis_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="produtos/"),
        ),
    ]
