# Generated by Django 4.1 on 2025-02-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quarto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("andar", models.IntegerField()),
                ("descricao", models.CharField(max_length=500)),
                ("valor_diaria", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ocupado", models.BooleanField(default=False)),
            ],
        ),
    ]
